version: '3'

services:
  microgenerator-q:
    build:
      context: ./ # Local
    #      context: https://github.com/elbosso/generator-microservices-q.git # Build from Github
    container_name: microgenerator-q
    hostname: microgenerator-q
#    ports:
#      - 8080:8080
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.generator-microservices-q.rule=Host(`generator-microservices-q.docker.lab`)"
      - "traefik.http.services.generator-microservices-q.loadbalancer.server.port=8080"
      - "traefik.docker.network=traefik_proxy"
    networks:
      - traefik_proxy

networks:
  traefik_proxy:
    external:
      name: traefik_proxy


